import turtle

wn = turtle.Screen()
wn.bgcolor("black")
player = turtle.Turtle()
player.color("purple")
player.penup()
player.setposition(250,0)
player.pendown()
player.setheading(90)
player.speed(6)
for i in range(4):
    player.circle(60,180)
    player.right(180)
player.hideturtle()
another = turtle.Turtle()
another.color("black")
another.penup()
another.setposition(250,0)
another.pendown()
another.setheading(90)
another.speed(6)
for i in range(4):
    another.circle(60,180)
    another.right(180)
look = turtle.Turtle()
look.color("red")
look.penup()
look.setposition(250,0)
look.pendown()
look.setheading(90)
look.speed(6)
for i in range(4):
    look.circle(60,180)
    look.right(180)
look.hideturtle()